version: "3.8"

services:
  web:
    build: .
    container_name: sentimental_analysis_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: sentimental_analysis_db
    restart: always
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
