services:
  - type: web
    name: sentiment-analysis
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd BACKEND && gunicorn new_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: HF_MODEL_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
